
das: ???
spat_time_domain: null
patch_size: ???
strides: null
ref_grid_var: null

cfg:
    _target_: xrpatcher._src.base.XRDAPatcher
    da: 
        _target_: ocn_tools._src.utils.data.interpstack_dataarrays
        dataarrays: '${...das}'
        ref_grid_var: '${...ref_grid_var}'
    domain_limits: 
        time: {_target_: builtins.slice, _args_: '${....spat_time_domain.time}'}
        lat: {_target_: builtins.slice, _args_: '${....spat_time_domain.lat}'}
        lon: {_target_: builtins.slice, _args_: '${....spat_time_domain.lon}'}
    patches: '${..patch_size}'
    strides: '${..strides}'
    
    
