#@package _global_.results

prepro:
  rec_ssh: {data_variable: rec_ssh}

select: 
  time: '${task.outputs.splits.test}'
  lat: '${task.outputs.domain.lat}'
  lon: '${task.outputs.domain.lon}'

degrid:
  _target_: ocn_tools._src.geoprocessing.gridding.grid_to_coord_based
  _partial_: true
  tgt_coord_based_ds: {inp: '${...outputs.eval.ref}', fns: ['${F.call}'], _partial_: false}

regrid:
  target_grid:
    domain: ${task.outputs.domain}
    period: ${task.outputs.splits.test}
    resolution: {lon: 0.05, lat: 0.05}

grid:
  target_grid:
    domain: ${task.outputs.domain}
    period: ${task.outputs.splits.test}
    resolution: {lon: 0.05, lat: 0.05}

postpro:
  select: '${..select.cfg}'
  grid: 
     fns: 
      - '${lib.processing.to_dataset}'
      - '${....grid.cfg}'
      - {_target_: "operator.itemgetter", _args_: ['ssh']}
  regrid: 
     fns: 
      - '${lib.processing.to_dataset}'
      - '${....regrid.cfg}'
      - {_target_: "operator.itemgetter", _args_: ['ssh']}
  degrid: 
     fns: 
      - '${lib.processing.to_dataset}'
      - '${....degrid}'
      - {_target_: "operator.itemgetter", _args_: ['ssh']}
  default:
     fns: 
      - '${...degrid}'
      - '${...select}'

outputs:
  eval: 
    ref: ???
    methods: {}


defaults:
    - /funcs@_global_.F
    - /processing/lib@_global_.lib.processing
    - /processing/components/select_where@select
    - /processing/components/grid_prepro@prepro.default
    - /processing/components/grid_prepro@prepro.rec_ssh
    - /processing/pipe@postpro.default
    - /processing/components/grid_to_grid@regrid
    - /processing/components/coord_based_to_grid@grid
    - /processing/pipe@postpro.regrid
    - /processing/pipe@postpro.grid
    - /processing/pipe@postpro.degrid
    - /processing/pipe@degrid.tgt_coord_based_ds
    - _self_
